### ISSUE TITLE
mysql can't connected 

### ISSUE THREAD

**Issue by ZhongqiXiao** [osteel/docker-tutorial-2#1]
Hello, I am a newbie in docker. I followed your instruction to run this project.When I opened `localhost` in chrome broswer i found that mysql couldn't be connected,it returned this error
···
Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1130] Host '172.18.0.4' is not allowed to connect to this MySQL server in /var/www/html/index.php:12 Stack trace: #0 /var/www/html/index.php(12): PDO->__construct('mysql:host=mysq...', 'project', 'project') #1 {main} thrown in /var/www/html/index.php on line 12
···
then i opened my terminal, i ran `docker exec -it docker exec -it dockertutorial2_mysql_1` bash, and i used the `DB_USERNAME` ,`DB_PASSWORD` and root,`DB_ROOT_PASSWORD` in `.env` file ,and i still couldn't login in to mysql
If you know what's going on this problem,please let me know.Thank you for your help!

**Comment by osteel** [comment]
Hey mate - sorry I guess I completely forgot about this. I'm not quite sure what could have gone wrong here - sometimes the MySQL database isn't available for another couple of minutes even after Docker Compose is done but this looks different.

Closing this as this is an old issue - let me know if this is still a problem for you though.
